name: Add publications by an author ID
description:  |
  Fill this form to add all publications by an author (using their Semantic Scholar ID) within a time frame.
title: "[Add publications by an author]"
labels: ["automatic-add-publications-by-author"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        This will add all publications by the author within the specified time frame using the Semantic Scholar API. To do this, a Semantic Scholar author ID is needed, which can be found by searching for the author in Semantic Scholar.
        
        Note: Since the API can only find the year of a publication, the month and day will be automatically set to January 1st.

        This form will automatically generate a PR that will be reviewed by the maintainers.
  - type: input
    id: start
    attributes:
      label: Start
      description: The start year of the time frame (inclusive).
      placeholder: "2020"
    validations:
      required: true

  - type: input
    id: end
    attributes:
      label: End
      description: The end year of the time frame (inclusive).
      placeholder: "2020"

  - type: input
    id: author_id
    attributes:
      label: Author ID
      description: The Semantic Scholar ID of the author.
      placeholder: "145113126"
    validations:
      required: true
